### PR TITLE
PD-4318 Fix date time creation when microtime has no decimals

### PR DESCRIPTION
**Pull request by estevejm**
More info: https://github.com/avadev/AvaTax-Calc-REST-PHP/issues/30

### CODE REVIEW

**Comment by ivannpaz** [comment]
👍

**Comment by loginesta** [comment]
:+1:

**Comment by nejo** [comment]
👍   U_U

**Comment by zerjio-mg** [comment]
:+1:

**Review by zerjio-mg — APPROVED** [review]

**Pull request merged**
